# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-23 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='分类名')),
                ('index', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='排序')),
            ],
            options={
                'verbose_name': '博客分类',
                'verbose_name_plural': '博客分类',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('words_count', models.IntegerField(default=0, verbose_name='字数')),
                ('allow_comment', models.BooleanField(default=True, verbose_name='允许评论')),
                ('vote_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='发表时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('pv', models.IntegerField(default=0, verbose_name='Page Views')),
                ('uv', models.IntegerField(default=0, verbose_name='User Views')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_posts', to='articles.ArticleCategory', verbose_name='博文种类')),
            ],
            options={
                'verbose_name': '博文',
                'verbose_name_plural': '博文',
            },
        ),
        migrations.CreateModel(
            name='ArticleTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='标签名')),
                ('index', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='排序')),
            ],
            options={
                'verbose_name': '博客标签',
                'verbose_name_plural': '博客标签',
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='tags',
            field=models.ManyToManyField(related_name='tags_posts', to='articles.ArticleTags'),
        ),
    ]
